DWAPlannerROS:
  holonomic_robot: false

  max_vel_x: 0.25
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_trans: 0.25
  min_vel_trans: 0.01
  max_vel_theta: 0.70
  min_vel_theta: 0.10

  acc_lim_x: 0.35
  acc_lim_y: 0.0
  acc_lim_theta: 1.0

  yaw_goal_tolerance: 0.15
  xy_goal_tolerance: 0.08
  latch_xy_goal_tolerance: true

  sim_time: 1.2
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 10
  vy_samples: 1
  vth_samples: 20

  path_distance_bias: 32.0
  goal_distance_bias: 24.0
  occdist_scale: 0.04
  forward_point_distance: 0.10
  stop_time_buffer: 0.3
  scaling_speed: 0.20
  max_scaling_factor: 0.20

  oscillation_reset_dist: 0.05
  prune_plan: true
  trans_stopped_vel: 0.02
  rot_stopped_vel: 0.05
  publish_traj_pc: false
  publish_cost_grid_pc: false
